CREATE TABLE vehiculo(
	MATRICULA VARCHAR(10) PRIMARY KEY,
	MARCA VARCHAR(20) NOT NULL,
	MODELO VARCHAR(20) NOT NULL,
	COLOR VARCHAR(20) NOT NULL

);

CREATE TABLE fichaTecnica (

    VIN VARCHAR(17) PRIMARY KEY,
	MATRICULA VARCHAR(10) NOT NULL,
	CARBURANTE VARCHAR(10) NOT NULL CHECK (CARBURANTE IN ('Gasolina', 'Diesel','Electrico')),
	CAMBIO VARCHAR(10) NOT NULL CHECK (CAMBIO IN ('Manual', 'Automatico')),
	NUMERO_ASIENTOS VARCHAR(9) NOT NULL,
	NUMERO_PUERTAS VARCHAR(10) NOT NULL,
    AÑO_MATRICULACION CHAR(4) NOT NULL, 
    ASEGURADORA VARCHAR(50) NOT NULL,
	POLIZA_SEGURO VARCHAR(20) NOT NULL,
	FECHA_PROXIMA_ITV CHAR(7) NOT NULL,
	FECHA_ULTIMA_REVISION DATE 
    
	FOREIGN KEY (MATRICULA) REFERENCES vehiculo(MATRICULA) 
);
